"""add personality and character master and join tables

Revision ID: 7eb842ba934a
Revises: bc2a96b17f0e
Create Date: 2026-07-19 03:04:21.610041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb842ba934a'
down_revision: Union[str, Sequence[str], None] = 'bc2a96b17f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_personalities_id'), 'personalities', ['id'], unique=False)
    op.create_table('user_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('user_personalities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'personality_id')
    )
    # ### end Alembic commands ###

    # 選択肢マスタの初期データ投入
    personalities_table = sa.table('personalities', sa.column('name', sa.String))
    characters_table = sa.table('characters', sa.column('name', sa.String))

    op.bulk_insert(personalities_table, [
        {'name': '協調性がある'},
        {'name': '慎重'},
        {'name': '好奇心旺盛'},
        {'name': '論理的'},
        {'name': '粘り強い'},
        {'name': '楽観的'},
    ])
    op.bulk_insert(characters_table, [
        {'name': 'リーダー経験'},
        {'name': '留学経験'},
        {'name': '資格保有'},
        {'name': '副業経験'},
        {'name': '登壇経験'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_personalities')
    op.drop_table('user_characters')
    op.drop_index(op.f('ix_personalities_id'), table_name='personalities')
    op.drop_table('personalities')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
