"""add permission_level to users

Revision ID: bc2a96b17f0e
Revises: 8d17516a6c71
Create Date: 2026-07-12 05:27:15.431369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2a96b17f0e'
down_revision: Union[str, Sequence[str], None] = '8d17516a6c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission_level')
    # ### end Alembic commands ###
